version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:5000"  # Порт на котором будет работать Flask приложение в контейнере
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Порт PostgreSQL
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
